title_name = "Dragon Ball Z: Burst Limit" # DBZ Burst Limit (v2.0 EU)
title_id = "424107DC" # BA-2012
hash = "C1C7D3D68031690D" # default.xex
#media_id = "6652B73F" # http://redump.org/disc/15956/

[[patch]]
    name = "60 FPS"
    desc = "Port of the similar patch originally made for RPCS3. Uncaps the framerate to 60. Some cutscenes and animations may force FPS to 30 again while they are playing."
    author = "illusion, ZEROx, Rei-san, Dunker961"
    is_enabled = false

    [[patch.be32]]
        address = 0x826de600
        value = 0x01 # FPS_CAP
    [[patch.be32]]
        address = 0x821dceb0
        value = 0x60000000 # Alternative fix for pause
    [[patch.be32]]
        address = 0x821dbe28
        value = 0x60000000 # Alternative fix for quitting the match
    [[patch.be32]]
        address = 0x8221d2f4
        value = 0x38600001 # RESET_CAP to 1
    [[patch.be32]]
        address = 0x82232e24
        value = 0x38600001 # RESET_CAP to 1
    [[patch.be32]]
        address = 0x822385d8
        value = 0x38600001 # RESET_CAP to 1
