title_name = "Midnight Club: Los Angeles" # MCLA
title_id = "545407F8" # TT-2040
hash = "B9BE89200A856E37" # default.xex
#media_id = "11CCEA2A" # Disc (USA): http://redump.org/disc/13311

[[patch]]
    name = "Game Speed Fix"
    desc = "Enables deltatime, preventing game speed fluctuations based on frame rate. See note about framerate patches in the README."
    author = "illusion, boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x821bf2c8
        value = 0x4800012c # b 0x821bdc34

[[patch]]
    name = "Disable Motion Blur"
    author = "illusion, boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x826cd258
        value = 0x38600000 # li r3,0x0
    [[patch.be32]]
        address = 0x826cd274
        value = 0x38600000 # li r3,0x0

[[patch]]
    name = "Disable Imposter Shadows - Performance Mode"
    desc = "Trees and other foliage won't cast shadows, resulting in a moderate performance boost."
    author = "boma"
    is_enabled = false

    [[patch.be16]]
        address = 0x823ccffc
        value = 0x4800

[[patch]]
    name = "Disable MSAA"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x823a6758
        value = 0x39600001

[[patch]]
    name = "Garage unlocker"
    desc = "Allows purchasing any vehicle whether it is locked or not. This also applies to the vehicle parts, but does not unlock the body parts."
    author = "LukeGoule"
    is_enabled = false

    [[patch.be32]]
        address = 0x826bcdc4
        value = 0x38600001
    [[patch.be32]]
        address = 0x826b94f8
        value = 0x39600001
