title_name = "Naruto Rise of a Ninja"
title_id = "555307E5" # IO-2001
hash = "AA17DB7395C0A667" # default.xex
#media_id = "12DF7A0D"

[[patch]]
    name = "21:9 Aspect Ratio"
    desc = "Ultrawidescreen."
    author = "Esppiral"
    is_enabled = false

    [[patch.be32]]
        address = 0x826f5108
        value = 0x3ed80000
